Team Members

*   Libin Kutty - Group 2
*   Ritu Gahir - Group 3
*   Viju Sudhi - Group 10


In [0]:
%tensorflow_version 2.x

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import time
import os

# Task 1

Given a 2D tensor of shape (?, n), extract the k (k <= n) highest values for each row into a tensor of shape (?, k). Hint: There might be a function to get the “top k” values of a tensor.

In [0]:
@tf.function
def task1():
  t1 = tf.random.uniform((10,10), minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)

  topk = tf.math.top_k(t1, k=5, sorted=True, name=None)

  tf.print(topk)

In [140]:
task1()

TopKV2(values=[[0.923631549 0.769995451 0.73755765 0.694040895 0.576379538]
 [0.872794271 0.768401265 0.765824914 0.763555765 0.689453483]
 [0.893523574 0.887966633 0.835084796 0.671398878 0.654708266]
 ...
 [0.937016606 0.924735785 0.910847306 0.904964566 0.849859238]
 [0.913367867 0.801814437 0.734445572 0.684016 0.598312497]
 [0.958501935 0.911828518 0.874616265 0.601439595 0.538943291]], indices=[[0 6 7 4 8]
 [2 1 8 5 3]
 [8 3 2 5 9]
 ...
 [4 8 6 3 5]
 [2 4 5 9 1]
 [0 3 8 6 7]])


# Task 2

Given a tensor of shape (?, n), find the argmax in each row and return a new tensor that contains a 1 in each of the argmax’ positions, and 0s everywhere else.


In [0]:
#@tf.function
def task2():
  t2 = tf.random.uniform((10,10), minval=0, maxval=None, dtype=tf.dtypes.float32)

  max = tf.math.argmax(t2, axis=1, output_type=tf.dtypes.int64, name=None)

  tf.print(max)

  z = tf.Variable(tf.zeros([10,10], tf.float32))
  for i, ind in enumerate(max):
    z[i,ind].assign(1.0)

  tf.print(z)

In [138]:
task2()

[8 8 1 ... 0 4 4]
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Task 3

As in 1., but instead of “extracting” the top k values, create a new tensor with shape (?, n) where all but the top k values for each row are zero. Try doing this with a 1D tensor of shape (n,) (i.e. one row) first. Getting it right for a 2D tensor is more tricky; consider this a bonus. Hint: You should look for a way to “scatter” a tensor of values into a different tensor. For two or more dimensions, you need to think carefully about the indices.

In [0]:
#@tf.function
def task3():

  t3 = tf.random.uniform((10,10), minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
  o3 = tf.Variable(tf.zeros(t3.shape, dtype=tf.dtypes.float32, name=None))

  topk = tf.math.top_k(t3, k=5, sorted=True, name=None)

  index = topk.indices
  tf.print(index)

  for i,ind in enumerate(index):
    for j in ind:
      o3[i,j].assign(t3[i,j])

  tf.print(o3)


In [136]:
task3()

[[7 3 5 0 8]
 [7 1 9 6 0]
 [9 4 7 2 6]
 ...
 [1 5 2 0 6]
 [5 9 1 7 6]
 [8 5 6 1 4]]
[[0.526077867 0 0 ... 0.878371716 0.485516429 0]
 [0.470251441 0.914644718 0 ... 0.988374 0 0.773713708]
 [0 0 0.625819325 ... 0.763696551 0 0.969604373]
 ...
 [0.53341794 0.978401542 0.84759438 ... 0 0 0]
 [0 0.709913254 0 ... 0.623722076 0 0.77282095]
 [0 0.329927802 0 ... 0 0.850263953 0]]


# Task 4

Implement an exponential moving average. That is, given a decay rate a and an input tensor of length T, create a new length T tensor where new[0] = input[0] and new[t] = a * new[t-1] + (1-a) * input[t] otherwise. Do not use tf.train.ExponentialMovingAverage.

In [0]:
#@tf.function
def task4():
  t4 = tf.random.uniform([10], minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
  a = 0.5

  z = tf.Variable(tf.zeros([10], tf.float32))

  for i,t in enumerate(t4):
    if i == 0:
      z[i].assign(t)
    else:
      z[i].assign(a * z[i-1] + (1-a) * t)

  tf.print(t4)

  tf.print(z)

In [133]:
task4()

[0.144263148 0.64008522 0.29204905 ... 0.292616367 0.77989614 0.355824351]
[0.144263148 0.392174184 0.342111617 ... 0.401101857 0.590499 0.473161668]


# Task 5

Find a way to return the last element in 4. without using loops. That is, return new[T] only – you don’t need to compute the other time steps (if you can avoid it).

In [0]:
#@tf.function
def task5():
  n = 10
  t5 = tf.random.uniform([n], minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
  a = 0.5

  z = tf.Variable(tf.zeros([n], tf.float32))

  tf.print(t5)
  tf.print(t5[n-1:])

  a = a * z[n-2:][0] + (1-a) * t5[n-1:][0]
  #z[n-1:].assign(a)

  tf.print(a)

In [131]:
task5()

[0.355605 0.494177461 0.958643556 ... 0.345623851 0.981263399 0.495944142]
[0.495944142]
0.247972071


# Task 6

Given three integer tensors x, y, z all of the same (arbitrary) shape, create a new tensor that takes values from y where x is even and from z where x is odd.

In [0]:
#@tf.function
def task6():
  n = tf.constant(2)
  m = tf.constant(5)
  x = tf.random.uniform((n,m), minval=0, maxval=10, dtype=tf.dtypes.int32, seed=None, name=None)
  y = tf.random.uniform((n,m), minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
  z = tf.random.uniform((n,m), minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)

  t6 = tf.Variable(tf.zeros((n,m), tf.float32))

  for i,a in enumerate(x):
    for j,b in enumerate(a):
      if (b % 2) == 0:
        t6[i,j].assign(y[i,j])
      else:
        t6[i,j].assign(z[i,j])

  tf.print('X')
  tf.print(x)
  tf.print('Y')
  tf.print(y)
  tf.print('Z')
  tf.print(z)

  tf.print('New Tensor')
  tf.print(t6)

In [127]:
task6()

X
[[9 2 7 9 2]
 [6 8 5 3 5]]
Y
[[0.244256377 0.543832779 0.762410522 0.145211697 0.511985421]
 [0.475984216 0.404932857 0.357961059 0.450443149 0.0869441]]
Z
[[0.595533729 0.525074959 0.962079644 0.27048707 0.217960119]
 [0.81360817 0.448634982 0.0760862827 0.829871535 0.78430438]]
New Tensor
[[0.595533729 0.543832779 0.962079644 0.27048707 0.511985421]
 [0.475984216 0.404932857 0.0760862827 0.829871535 0.78430438]]


# Task 7

Given a tensor of arbitrary and unknown shape (but at least one dimension), return 100 if the last dimension has size > 100, 12 if the last dimension has size <= 100 and > 44, and return 0 otherwise.

In [0]:
@tf.function
def task7(): 
  n = tf.random.uniform([1], minval=1, maxval=200, dtype=tf.dtypes.int32, seed=None, name=None)
  m = tf.random.uniform([1], minval=1, maxval=200, dtype=tf.dtypes.int32, seed=None, name=None)

  t7 = tf.random.uniform((n[0],m[0]), minval=0, maxval=10, dtype=tf.dtypes.float32, seed=None, name=None)

  #last_dim = t7.shape[-1]
  last_dim = tf.shape(t7)[-1]

  if tf.math.greater(last_dim, 100):
    value = 100
  elif tf.math.less_equal(last_dim, 100) and tf.math.greater(last_dim, 44):
    value = 12
  else:
    value = 0

  tf.print(last_dim)
  tf.print(value)

In [163]:
task7()

79
12


# Task 8

As 7., but also create three global counts (integers), where count i should grow by 1 if condition i happened. Run the function from 7. multiple times to test whether your counting works. Now, add a @tf.function decorator to the function from 7. Does your counter still work? If not, why not? Can you change it so it does work?

In [0]:
@tf.function
def task8():
  count1 = 0
  count2 = 0
  count3 = 0
  for _ in range(10): 
    n = tf.random.uniform([1], minval=1, maxval=200, dtype=tf.dtypes.int32, seed=None, name=None)
    m = tf.random.uniform([1], minval=1, maxval=200, dtype=tf.dtypes.int32, seed=None, name=None)

    t8 = tf.random.uniform((n[0],m[0]), minval=0, maxval=10, dtype=tf.dtypes.float32, seed=None, name=None)
    last_dim = tf.shape(t8)[-1]

    if tf.math.greater(last_dim, 100):
      value = 100
      count1 += 1
    elif tf.math.less_equal(last_dim, 100) and tf.math.greater(last_dim, 44):
      value = 12
      count2 += 1
    else:
      value = 0
      count3 += 1

  tf.print('Count 1:',count1)
  tf.print('Count 2:', count2)
  tf.print( 'Count 3:', count3)


In [161]:
task8()

Count 1: 6
Count 2: 1
Count 3: 3


# Task 9

Given two 1D tensors of equal length n, create a tensor of shape (n, n) where element i,j is the ith element of the first tensor minus the jth element of the second tensor. No loops! Hint: Tensorflow supports broadcasting much like numpy.

In [0]:
@tf.function
def task9():
  n = 2

  x = tf.random.uniform([n], minval=0, maxval=10, dtype=tf.dtypes.int32, seed=None, name=None)
  y = tf.random.uniform([n], minval=0, maxval=10, dtype=tf.dtypes.int32, seed=None, name=None)

  t9_1 = tf.broadcast_to(tf.math.add(x[0],-y), [n])
  t9_2 = tf.broadcast_to(tf.math.add(x[-1],-y), [n])

  t9 = tf.stack([t9_1, t9_2])


  tf.print(x)
  tf.print(y)
  tf.print(t9)


In [159]:
task9()

[6 2]
[7 5]
[[-1 1]
 [-5 -3]]


# Task 10

Implement dot product attention: You are given a sequence of encoder states h of shape batch x time x features and the last decoder state s of shape batch x features. Compute the attention weights alpha where alpha[:, i] is equal to h[:, i] * s where * is the dot product between vectors (in this case we also have a batch dimension so the dot product should be between the corresponding vectors within the batch). That is, alpha should be of shape batch x time and alpha[:, i] should contain the attention weights for encoder time step i.


In [0]:
@tf.function
def task10(alpha):
  batch = 10
  time = 3
  feature = 5

  h = tf.random.uniform([batch, time, feature], minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
  s = tf.random.uniform([batch, feature], minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
  s = tf.transpose(s)

  for i in tf.range(time):
    x = tf.matmul(h[:, i,:], s)
    sum = tf.reduce_sum(x,1)
    alpha[:, i].assign(sum)

  tf.print(alpha)


In [54]:
batch = 10
time = 3
alpha = tf.Variable(tf.zeros((batch, time), tf.float32))
task10(alpha)

[[10.6033783 7.60375309 6.68714714]
 [8.33918285 11.3527851 10.0338058]
 [9.6647768 11.2956762 6.94149637]
 ...
 [12.9316263 10.1323576 12.8843822]
 [16.5914326 12.8762074 8.01624775]
 [8.04395199 11.8333321 8.76329803]]
